### ISSUE TITLE
Update option issue.

### ISSUE THREAD

**Issue by Sehraan** [Suwayomi/Tachidesk-Server-preview#5]
In the newest Preview Version of Tachidesk when you open updates it only shows a white screen and nothing else. @AriaMoradi 
![Screenshot 2021-11-13 131918](https://user-images.githubusercontent.com/93523756/141610712-f72471f2-22b9-45f3-a522-e5d8e2b3c7fe.png)

**Comment by AriaMoradi** [comment]
Fixed in r1035
